services:
  - type: web
    name: thera-backend
    env: node
    buildCommand: npm install && pip install -r requirements.txt
    startCommand: node server.js
    envVars:
      - key: DB_HOST
        value: 35.185.8.133
      - key: DB_USER
        value: root
      - key: DB_PASSWORD
        value: Atenas9democraci.
      - key: DB_NAME
        value: thera_final_database
      - key: DB_PORT
        value: 3306
      - key: CLIENT_API_KEY
        value: 9f8a24bcfb9d4c8e97f6c4c7e2ac9ed7d64fbd3d2ad1f1ef68e8a58273f5b649
